import { Box, Input, Flex, Text, Button } from "@chakra-ui/react";
import React, { useState } from "react";
import Head from "next/head";
import Header from "../Components/Header";

async function verifyCert () {
   let  cc = "229906MN"
 let bodyContent = new FormData()
 bodyContent.append("cert_number",cc)

 let response = await fetch(`https://florintechcomputercollege.com/api/api_verifycertificate.php`,{
 
  // cert_number:"229906MN",
  
    method: 'POST', 
    
  
  body:bodyContent,
})

let data = await response.json()
console.log(data);

}
  // setVerifying(true)
 


// .then((a)=>{return a.json()}).then((result)=>{
  
//  console.log((result));
  
//   ;})

//   console.log("working");
// }

function verifycertificate() {
  const [setVerifying,verifying] = useState(false)
  return (
    <Box>
      <Head>
        <title>verify certificate | Florintech Computer College</title>
        <meta
          name="Florintech Computer College"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Flex justifyContent="center">
        <Box>
          <Text fontSize="30px">Verify Certificate</Text>
          <Input
            placeholder="Enter Certificate Number"
            variant="outline"
          
          />
          <Button  variant="outline"
         
          onClick={verifyCert}
           m="40px" 
           textAlign="center"
            loadingText="verifying.."
            colorScheme="teal">Verify</Button>
        </Box>
      </Flex>
    </Box>
  );
}

export default verifycertificate;
