import { Box, Input, Flex, Text, Button } from "@chakra-ui/react";
import React, { useState } from "react";
import Head from "next/head";
import Header from "../Components/Header";

const verifyCert = () =>{
  let  cc = {cert_number:"229906MN"}
  // setVerifying(true)
fetch(`https://florintechcomputercollege.com/api/api_verifycertificate.php`,{
 
  // cert_number:"229906MN",
  
    method: 'POST', 
    
  
  body: JSON.stringify(cc),
}).then((a)=>{return a.json()}).then((result)=>{
  
 console.log((result));
  
  ;})

  console.log("working");
}

function verifycertificate() {
  const [setVerifying,verifying] = useState(false)
  return (
    <Box>
      <Head>
        <title>verify certificate | Florintech Computer College</title>
        <meta
          name="Florintech Computer College"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Flex justifyContent="center">
        <Box>
          <Text fontSize="30px">Verify Certificate</Text>
          <Input
            placeholder="Enter Certificate Number"
            variant="outline"
          
          />
          <Button  variant="outline"
         
          onClick={verifyCert}
           m="40px" 
           textAlign="center"
            loadingText="verifying.."
            colorScheme="teal">Verify</Button>
        </Box>
      </Flex>
    </Box>
  );
}

export default verifycertificate;
